## - Introdução ao Numpy

##### - Numpy é uma biblioteca de álgebra libear para python
##### - É o bloco de construção de todas as outras bibliotecas de análise de dados
##### - É extremamente rápida, uma vez que seus prncipais métodos foram compilados em C.

*Numpy arrays serão nossa principal ferramenta
*Numpy arrays essencialmente vêm de duas formas: vetores e matrizes
*Vetores são estritamente arrays de 1 dimensão e matrizes são de duas dimensões

In [2]:
import numpy as np

In [3]:
minhas_lista = [1, 2, 3]

In [5]:
np.array(minhas_lista)

array([1, 2, 3])

###### - para criar um array de duas dimensões, declaramos uma lista de lista e usamos o método array

In [6]:
minha_matriz = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]

In [7]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###### - Criando arrays de uma maneira mais fácil

##### -  Método do numpy

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
arr = np.zeros(5)

In [11]:
arr

array([0., 0., 0., 0., 0.])

Para criar arrays de duas dimensões usando métodos, devemos passar uma tupla como parâmetro.

In [12]:
arr = np.zeros((5,5))

In [13]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [17]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

###### - Random

É uma sub-biblioteca dentro do numpy. É utilizada para gerar valores aleatórios. 

In [18]:
np.random.rand (5)

array([0.13564533, 0.78553754, 0.56055058, 0.91695508, 0.55782118])

Random pode ser utilizado para fazer matrizes

In [19]:
np.random.rand(4, 3, 3)

array([[[0.09951034, 0.66958108, 0.32832581],
        [0.13137644, 0.54321086, 0.22828285],
        [0.99147517, 0.42706081, 0.69724903]],

       [[0.87663343, 0.47895973, 0.42000254],
        [0.47506299, 0.10491755, 0.20808014],
        [0.46205818, 0.63840456, 0.66954105]],

       [[0.31131264, 0.20942272, 0.42166165],
        [0.69953258, 0.53091922, 0.27055798],
        [0.81618486, 0.6230914 , 0.87074294]],

       [[0.75273075, 0.66640679, 0.79960275],
        [0.78562023, 0.95492866, 0.90210138],
        [0.30151974, 0.62971091, 0.61886742]]])

In [21]:
np.random.randint (0, 60, 6)

array([23, 27, 27,  5,  5,  4])

##### - Reshape

In [22]:
arr = np.random.rand(25)

In [23]:
arr

array([0.80587442, 0.01614304, 0.01155333, 0.73000616, 0.0625813 ,
       0.07957363, 0.87450283, 0.41096164, 0.88389271, 0.49341002,
       0.62002792, 0.0552684 , 0.46165216, 0.98548128, 0.52518747,
       0.69710912, 0.41765386, 0.81192718, 0.8460555 , 0.24071453,
       0.35033729, 0.84501217, 0.34852455, 0.33743746, 0.84097341])

In [24]:
arr.reshape((5,5))

array([[0.80587442, 0.01614304, 0.01155333, 0.73000616, 0.0625813 ],
       [0.07957363, 0.87450283, 0.41096164, 0.88389271, 0.49341002],
       [0.62002792, 0.0552684 , 0.46165216, 0.98548128, 0.52518747],
       [0.69710912, 0.41765386, 0.81192718, 0.8460555 , 0.24071453],
       [0.35033729, 0.84501217, 0.34852455, 0.33743746, 0.84097341]])

In [25]:
arr.shape

(25,)

In [26]:
arr = arr.reshape((5,5))

In [27]:
arr

array([[0.80587442, 0.01614304, 0.01155333, 0.73000616, 0.0625813 ],
       [0.07957363, 0.87450283, 0.41096164, 0.88389271, 0.49341002],
       [0.62002792, 0.0552684 , 0.46165216, 0.98548128, 0.52518747],
       [0.69710912, 0.41765386, 0.81192718, 0.8460555 , 0.24071453],
       [0.35033729, 0.84501217, 0.34852455, 0.33743746, 0.84097341]])

In [28]:
arr.shape

(5, 5)

In [29]:
arr.max()

0.9854812802887236

In [30]:
arr.min()

0.011553329749943053

In [31]:
arr.argmax()

13

In [32]:
arr.argmin()

2

## - Indexação em Numpy 

In [35]:
arr = np.arange(0, 30, 3)

In [36]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [37]:
arr[3]

9

In [38]:
arr[2:5]

array([ 6,  9, 12])

In [39]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [40]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [41]:
arr[2:] = 100

In [42]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

com arrays bidimensionais

In [43]:
arr = np.arange(50).reshape((5,10))

In [44]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [46]:
arr2 = arr[:3]

In [47]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [48]:
arr2[:] = 100

In [49]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [50]:
arr3 = np.arange(50).reshape((5,10))

In [51]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr4 = arr3[:3].copy()

In [53]:
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [54]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr4[:] = 100

In [56]:
arr4

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [57]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [58]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [59]:
arr3 > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

## - Operações entre Arrays

In [60]:
arr = np.arange(0,16)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
 arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [63]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [65]:
arr/arr

<ipython-input-65-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

o resultada acima é devido a tentativa de dividir zero por zero o que não gerou um erro mas sim um aviso. (nan)

As operações entre arrays são realizadas indice a indice, portanto é necessário que os arrays tenham o mesmo tamanho. 

In [66]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [67]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

existem diversas operações matematicas que podem ser utilizadas atraves do numpy, antes de resolver um problema procure saber se já existe um método com para a operação desejada. 